name: qirrunner-publish-$(BuildId)

trigger: none
pr: none

variables:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN_VERSION: "1.78"
  PYTHON_VERSION: "3.11"
  AUDITWHEEL_TAG: "manylinux_2_31_x86_64"

jobs:
- job: "Build"
  strategy:
    matrix:
      linux_x64:
        imageName: 'ubuntu-20.04'
        arch: x86_64
      mac_x64:
        imageName: 'macOS-latest'
        arch: x86_64
        ARCHFLAGS: '-arch x86_64'
      windows:
        imageName: 'windows-latest'
        arch: x86_64
  pool:
    vmImage: $(imageName)
  variables:
    arch: $(arch)
  timeoutInMinutes: 300

  steps:
  # common init steps
  - task: RustInstaller@1
    inputs:
      rustVersion: ms-$(RUST_TOOLCHAIN_VERSION)
      cratesIoFeedOverride: $(cratesIoFeedOverride)
      toolchainFeed: $(toolchainFeed)
    displayName: Install Rust toolchain

  - script: |
      rustc --version
      rustc --print target-list
    displayName: View rust target info

  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(PYTHON_VERSION)

# prerequisites for building

  - pwsh: |
      Write-Host "##vso[task.setvariable variable=MACOSX_DEPLOYMENT_TARGET;]10.12"
    displayName: Configure Environment (MACOSX_DEPLOYMENT_TARGET x86_64)
    condition: eq(variables['Agent.OS'], 'Darwin')

  - template: llvm.yml
    parameters:
      version: "14"
      os: $(imageName)
      arch: $(arch)
      directory: $(Build.SourcesDirectory)/target/llvm14-0
      arch_flags: $(ARCHFLAGS)

# build the project

  - script: |
      cargo build -vv --release
    displayName: Build (non-Mac)
    condition: succeeded()

# test the project

  - script: |
      cargo test -vv --release -- --nocapture
    displayName: Test (non-Mac)
    condition: succeeded()

# package the project

  - script: |
      python -m pip install -U pip
      python -m pip install -r pip/requirements.txt
    displayName: Install Python packages
    condition: succeeded()

  - script: |
      python -m build --verbose --wheel ./pip
    displayName: Create Non-Linux Python wheel
    condition: and(succeeded(), ne(variables['Agent.OS'], 'Linux'))

  - script: |
      python -m pip install -r pip/requirements-manylinux.txt
      python -m build --verbose --wheel --outdir target/raw-wheels ./pip
      python -m build --verbose --sdist --outdir target/wheels ./pip
      auditwheel repair --plat $(AUDITWHEEL_TAG) --wheel-dir target/wheels target/raw-wheels/*.whl
    displayName: Create Linux Python wheel and run Auditwheel
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

# test the Python packages

  - script: |
      python -m pip install -r pip/requirements-test.txt
      python -m pip install --force-reinstall --no-index --find-links=target/wheels qirrunner
      python -m pytest --verbose pip
    displayName: Test Python packages
    condition: succeeded()

# publish the python artifacts

  - script: |
      dir target\wheels\*
    displayName: List Py Packages on Win
    condition: eq(variables['Agent.OS'], 'Windows_NT')

  - script: |
      ls target/wheels/*
    displayName: List Py Packages on non-Win
    condition: ne(variables['Agent.OS'], 'Windows_NT')

  - publish: $(System.DefaultWorkingDirectory)/target/wheels
    artifact: Wheels.Mac.${{ variables['arch'] }}
    displayName: Upload Python Artifacts Mac
    condition: eq(variables['Agent.OS'], 'Darwin')

  - publish: $(System.DefaultWorkingDirectory)/target/wheels
    artifact: Wheels.Win.${{ variables['arch'] }}
    displayName: Upload Python Artifacts Win
    condition: eq(variables['Agent.OS'], 'Windows_NT')

  - publish: $(System.DefaultWorkingDirectory)/target/wheels
    artifact: Wheels.Linux.${{ variables['arch'] }}
    displayName: Upload Python Artifacts Linux
    condition: eq(variables['Agent.OS'], 'Linux')

# Publish stdlib

  - pwsh: |
      New-Item -Path $(Build.SourcesDirectory)/target/stdlib -ItemType Directory -Force
      Copy-Item -Path $(Build.SourcesDirectory)/stdlib/include/qir_stdlib.h -Destination $(Build.SourcesDirectory)/target/stdlib -Force
      Copy-Item -Path $(Build.SourcesDirectory)/pip/NOTICE.txt -Destination $(Build.SourcesDirectory)/target/stdlib -Force
      Copy-Item -Path $(Build.SourcesDirectory)/LICENSE -Destination $(Build.SourcesDirectory)/target/stdlib -Force
    displayName: Organize qir-stdlib artifacts (all platforms)

  - pwsh: |
      Copy-Item -Path $(Build.SourcesDirectory)/target/release/libqir_stdlib.a -Destination $(Build.SourcesDirectory)/target/stdlib -Force
    displayName: Organize qir-stdlib artifacts (Linux/Mac)
    condition: ne(variables['Agent.OS'], 'Windows_NT')

  - pwsh: |
      Copy-Item -Path $(Build.SourcesDirectory)/target/release/qir_stdlib.lib -Destination $(Build.SourcesDirectory)/target/stdlib -Force
      Copy-Item -Path $(Build.SourcesDirectory)/stdlib/include/qir_stdlib.def -Destination $(Build.SourcesDirectory)/target/stdlib -Force
    displayName: Organize qir-stdlib artifacts (Windows)
    condition: eq(variables['Agent.OS'], 'Windows_NT')

  - publish: $(System.DefaultWorkingDirectory)/target/stdlib
    artifact: qir-stdlib-${{ variables['Agent.OS'] }}-${{ variables['arch'] }}
    displayName: Upload stdlib Artifacts

- job: "Merge"
  dependsOn:
  - Build
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - download: current
    artifact: Wheels.Win.x86_64
    displayName: Download x86_64 Python Artifacts Win

  - download: current
    artifact: Wheels.Mac.x86_64
    displayName: Download Python Artifacts Mac

  - download: current
    artifact: Wheels.Linux.x86_64
    displayName: Download x86_64 Python Artifacts Linux

  - script: |
      mkdir -p                                  target/wheels
      mv ../Wheels.Linux.x86_64/*manylinux*.whl target/wheels
      mv ../Wheels.Linux.x86_64/*.tar.gz        target/wheels
      mv ../Wheels.Win.x86_64/*.whl             target/wheels
      mv ../Wheels.Mac.x86_64/*.whl             target/wheels
      ls                                        target/wheels/*
    displayName: Move Py Artifacts to Publishing Dir

  - publish: $(System.DefaultWorkingDirectory)/target/wheels
    artifact: wheels
    displayName: Upload Python Artifacts


- job: "Approval"
  dependsOn:
  - Build
  - Merge

  pool: server
  timeoutInMinutes: 1440 # job times out in 1 day
  steps:
  - task: ManualValidation@0
    timeoutInMinutes: 1440 # task times out in 1 day
    inputs:
      notifyUsers: ''
      instructions: 'Please verify artifacts and approve the release'
      onTimeout: 'reject'


- job: "Publish_Python_Packages"
  dependsOn: Approval
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - download: current
    artifact: wheels
    displayName: Download Python Artifacts

  - script: |
      mkdir -p                            target/wheels
      mv ../wheels/*.*                    target/wheels
      ls                                  target/wheels/*
    displayName: Move Py Artifacts to Publishing Dir

# Add ESRP steps here

  - task: EsrpRelease@4
    displayName: Publish Py Packages
    inputs:
     ConnectedServiceName: 'ESRP_Release'
     Intent: 'PackageDistribution'
     ContentType: 'PyPi'
     FolderLocation: '$(System.DefaultWorkingDirectory)/target/wheels'
     Owners: '$(OwnerPersonalAlias)@microsoft.com'  # NB: Group email here fails the task with non-actionable output.
     Approvers: 'billti@microsoft.com'
     # Auto-inserted Debugging defaults:
     ServiceEndpointUrl: 'https://api.esrp.microsoft.com'
     MainPublisher: 'QuantumDevelpmentKit'          # ESRP Team's Correction (including the critical typo "Develpm").
     DomainTenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47'
